FROM postgres:15.2-alpine

LABEL author="Arturo Lopez <lgzarturo@gmail.com>"
LABEL description="Postgres Image for personal use"
LABEL version="1.0"

# Copy the sql files to the docker-entrypoint-initdb.d folder
# COPY *.sql /docker-entrypoint-initdb.d/
