spring:
  profiles:
    active: development
  data:
    rest:
      basePath: /api
      returnBodyOnCreate: false
      returnBodyOnUpdate: false
      detection-strategy: ANNOTATED
app:
  name: Personal API Rest
  version: 0.0.3-SNAPSHOT
  description: API REST with Spring Boot to manage my personal data and portfolio projects
  url: https://lgzarturo.com
  email: lgzarturo@gmail.com
