# Logging and Debug Configuration
spring.config.import: optional:secrets.properties
debug: false
logging:
  file:
    name: logs/development.log
  level:
    root: INFO
    com.lgzarturo.api.personal: DEBUG
    com.springboot.application: DEBUG
    com.springboot.security: DEBUG
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.hibernate: WARN
    org.hibernate.type: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.stat: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    com.zaxxer.hikari: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
# Server Configuration
server:
  port: 8080
  mvc:
    async:
      request-timeout: 120000ms
  tomcat:
    keep-alive-timeout: 120000ms
  compression:
    enabled: true
    mime-types:
      - application/json
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-exception: false
    include-stacktrace: NEVER
# Spring Configuration
spring:
  security:
    debug: true
  main:
    banner-mode: CONSOLE
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 10
        query:
          in_clause_parameter_padding: true
          plan_cache_max_size: 1
        order_updates: true
        jdbc:
          batch_size: 30
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 10
  servlet:
    multipart:
      enabled: true
      location: /tmp
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB
  h2:
    console:
      enabled: false
# Actuator Configuration
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
# API Application Configuration
api:
  service:
    configuration:
      debug: true
  path:
    files: /Users/revenatium/dev/lgzarturo/data/
    uri: /static/images/
  security:
    jwt:
      secret: 25442A472D4B6150645367556B58703273357638792F423F4528482B4D625165
      issuer: personal-api
      expiration: 7_200_000
  token-secret: bPeShVmYq3t6w9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: true
