# Reservations API Documentation
# Create Reservation
POST /api/v1/reservations HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "clientId": 1,
    "hotelId": 1,
    "totalNights": 5,
    "totalPersons": 4
}

###
# Get Reservation
GET /api/v1/reservations/{{reservationId}} HTTP/1.1
Host: localhost:8080
Authorization: Bearer {{token}}
